#!/bin/sh

set -ev

SERVER_JAR="$SERVER_ROOT/$SERVER_ARTIFACT"

/bin/env_parse /etc/${SERVER_CONFIG}.j2
/bin/env_parse /etc/${LOGBACK_CONFIG}.j2

exec su socrata -c "exec /usr/bin/java \
    -Xmx${JAVA_XMX} \
    -Xms${JAVA_XMX} \
    -Dconfig.file=/etc/${SERVER_CONFIG} \
    -Dlogback.configurationFile=/etc/${LOGBACK_CONFIG} \
    -jar $SERVER_JAR"
