#!/bin/sh

set -ev

SERVER_JAR="$SERVER_ROOT/$SERVER_ARTIFACT"

/bin/env_parse /etc/${SERVER_CONFIG}.j2
/bin/env_parse /etc/${LOGBACK_CONFIG}.j2

exec su socrata -c "exec /usr/bin/java \
    -Xmx${JAVA_XMX} \
    -Xms${JAVA_XMX} \
    -Dconfig.file=/etc/${SERVER_CONFIG} \
    -Dlogback.configurationFile=/etc/${LOGBACK_CONFIG} \
    -Djava.net.preferIPv4Stack=true \
    -Dcom.sun.management.jmxremote.port=${JMX_PORT} \
    -Dcom.sun.management.jmxremote.rmi.port=${JMX_PORT} \
    -Dcom.sun.management.jmxremote.ssl=false \
    -Dcom.sun.management.jmxremote.authenticate=false \
    -Djava.rmi.server.hostname=${ARK_HOST:-localhost} \
    -jar $SERVER_JAR"
